# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='tel',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
